version: '3.8'

volumes:
  postgresql:

services:
  postgres:
    image: bitnami/postgresql:17.5.0
    container_name: postgres
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: master
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data
